-- 저자 별 카테고리 별 매출액 집계하기

SELECT AUTHOR.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY, 
       SUM(BOOK_SALES.SALES * BOOK.PRICE) as TOTAL_SALES
FROM BOOK, AUTHOR, BOOK_SALES
WHERE BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
  AND BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
  AND BOOK_SALES.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY AUTHOR.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY
ORDER BY AUTHOR.AUTHOR_ID ASC, BOOK.CATEGORY DESC;
